version: '3'

volumes:
  node_modules_bank-account-helper:
  node_modules_bank-robber:


services:
  bank-account-helper:
    image: bank-account-helper
    build: ./bank-account-helper
    links:
      - bank-robber
    depends_on:
      - bank-robber
    volumes:
      - ./bank-account-helper:/build
      - node_modules_bank-account-helper:/build/node_modules/
    ports:
      - "3000:3000"
  bank-robber:
    image: bank-robber
    build: ./bank-robber
    volumes:
      - ./bank-robber:/build
      - node_modules_bank-robber:/build/node_modules/
    ports:
      - "5000:5000"